---
- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Check exist ZSH bin
  ansible.builtin.stat:
    path: /bin/zsh
  register: zsh_bin_file

- name: Change defaul shell
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
  when: zsh_bin_file.stat.exists
