---
- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service_node.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: "0755"

- name: Enable and check K3s service
  ansible.builtin.service:
    name: k3s-node
    state: started
    enabled: true
