---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Download k3s binary arm64
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/latest/download/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/latest/download/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"
  when:
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Download k3s binary armhf
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/latest/download/k3s-armhf
    checksum: https://github.com/k3s-io/k3s/releases/latest/download/sha256sum-arm.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"

# Check rasspberry pi and distribution

- name: Test for raspberry pi /proc/cpuinfo
  ansible.builtin.command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
  register: grep_cpuinfo_raspberrypi
  failed_when: false
  changed_when: false

- name: Test for raspberry pi /proc/device-tree/model
  ansible.builtin.command: grep -E "Raspberry Pi" /proc/device-tree/model
  register: grep_device_tree_model_raspberrypi
  failed_when: false
  changed_when: false

- name: Set raspberry_pi fact to true
  ansible.builtin.set_fact:
    raspberry_pi: true
  when: grep_cpuinfo_raspberrypi.rc == 0 or grep_device_tree_model_raspberrypi.rc == 0

- name: Execute Ubuntu related tasks on the Raspberry Pi
  ansible.builtin.include_tasks: prereq/Ubuntu.yml
  when: >
    raspberry_pi|default(false) and
    ( ansible_facts.lsb.id|default("") == "Ubuntu" or
      ansible_facts.lsb.description|default("") is match("Ubuntu.*") )

- name: Execute Raspbian related tasks on the Raspberry Pi
  ansible.builtin.include_tasks: prereq/Raspbian.yml
  when: >
    raspberry_pi | default(false) and
    ( ansible_facts.lsb.id | default("") == "Raspbian" or
      ansible_facts.lsb.description | default("") is match("[Rr]aspbian.*") )
