---
- name: Enable packet forwording for IPv4
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Install WireGuard
  ansible.builtin.package:
    name: wireguard-tools
    state: present

- name: Create WireGuard configurations directory
  ansible.builtin.file:
    dest: /etc/wireguard
    state: directory
    owner: root
    mode: "0600"

- name: Create WireGuard config
  ansible.builtin.template:
    dest: "/etc/wireguard/{{ wg_interface_name }}.conf"
    src: wg_server.conf.j2
    owner: root
    mode: "0600"

- name: Create PostUp script
  ansible.builtin.template:
    dest: "/etc/wireguard/add-nat-routing.sh"
    src: add-nat-routing.sh.j2
    owner: root
    mode: "0700"
  when: enable_nat

- name: Create PostDown script
  ansible.builtin.template:
    dest: "/etc/wireguard/remove-nat-routing.sh"
    src: remove-nat-routing.sh.j2
    owner: root
    mode: "0700"
  when: enable_nat

- name: Setup FirewallD fot WireGuard
  when: ansible_os_family == 'RedHat'
  block:
    - name: Allow WireGuard service for FirewallD public zone
      ansible.posix.firewalld:
        port: "{{ wg_server_port }}/udp"
        state: enabled
        permanent: true
        immediate: true

- name: Reload WireGuard and enable on boot
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: true
    state: reloaded
  tags:
    - wireguard-reload
